name: Run ls command in a specific directory on EC2

on:
  workflow_dispatch: # This allows you to manually trigger the workflow

jobs:
  run-ls:
    runs-on: self-hosted

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: SSH into EC2 and run ls in a specific directory
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-3-70-238-154.eu-central-1.compute.amazonaws.com 'ls /home/ubuntu' > ls_output.txt
          cat ls_output.txt

      - name: SSH into EC2 and run unseal_vault.sh script
        run: |
          ssh -o StrictHostKeyChecking=no deployer@ec2-3-70-238-154.eu-central-1.compute.amazonaws.com './cron_scripts/unseal_vault.sh'
