name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Run config.sh
        run: |
          ./config.sh --url https://github.com/input-output-hk/moe-world --token AHGHLBR2Q3FKVDEWS7QOI4TFD7QFS
        working-directory: /path/to/your/script/folder

      - name: Deploy code to EC2
        run: |
          scp -i github_action_deploy_key -o StrictHostKeyChecking=no -r ./your-code-folder/ username@your-ec2-instance-ip:/path/to/destination/
          ssh -i github_action_deploy_key -o StrictHostKeyChecking=no username@your-ec2-instance-ip 'bash -s' < deploy-script.sh
