name: Run unseal_vault.sh script on EC2

on:
  workflow_dispatch: # This allows you to manually trigger the workflow

jobs:
  run-script:
    runs-on: self-hosted

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Add SSH Key to Agent
        run: |
          ssh-add - <<< "${{ secrets.DEPLOY_KEY }}"

      - name: SSH into EC2 and run unseal_vault.sh script
        run: |
          ssh -o StrictHostKeyChecking=no deployer@ec2-3-70-238-154.eu-central-1.compute.amazonaws.com './cron_scripts/unseal_vault.sh'
